(() => {
  const species=[
    {id:'little-egret',name:'小白鹭',scientific:'Egretta garzetta',emoji:'🪶',status:'无危（LC）',habitat:'潮间带、浅水塘、红树林边缘',image:'little-egret.jpg',source:'https://en.wikipedia.org/wiki/Little_egret',intro:['小白鹭是深圳湾常见的中型白色鹭鸟。它的嘴细长而黑，腿部黑色，脚趾鲜黄色，飞行时颈部会缩成 S 形。','它们常在浅水中缓慢移动，用脚搅动水底，再迅速啄取小鱼、虾和水生昆虫。深圳湾退潮后的浅滩与红树林水道为它们提供了丰富食物。'],facts:['黄色脚趾像穿了一双醒目的“黄袜子”','繁殖期头后会长出两根细长饰羽','会用脚在水中抖动，惊出藏在泥沙中的猎物'],tip:'观鸟时保持安静，不要进入浅滩追赶觅食中的鹭鸟。'},
    {id:'black-winged-stilt',name:'黑翅长脚鹬',scientific:'Himantopus himantopus',emoji:'🦩',status:'无危（LC）',habitat:'浅水湿地、鱼塘、盐沼',image:'black-winged-stilt.jpg',source:'https://en.wikipedia.org/wiki/Black-winged_stilt',intro:['黑翅长脚鹬拥有极为修长的粉红色双腿，白色身体和黑色翅膀形成鲜明对比，是浅水湿地中非常醒目的涉禽。','它们用细直的嘴在水面和泥中啄食昆虫、甲壳动物及其他小型水生动物，在深圳湾及周边湿地可见其活动记录。'],facts:['双腿长度在鸟类中比例非常突出','受惊时会发出连续而尖锐的警戒声','常在水深较浅、视野开阔的区域成群觅食'],tip:'繁殖季不要靠近可能的巢区，遛狗时请全程牵绳。'},
    {id:'pied-avocet',name:'反嘴鹬',scientific:'Recurvirostra avosetta',emoji:'🐦',status:'无危（LC）',habitat:'河口、盐沼、潮间带',image:'pied-avocet.jpg',source:'https://en.wikipedia.org/wiki/Pied_avocet',intro:['反嘴鹬具有黑白相间的羽色和明显向上弯曲的细长嘴，外形优雅，容易辨认。','觅食时，它会把嘴放入浅水中左右扫动，筛取小型甲壳动物和水生昆虫。深圳湾是东亚—澳大利西亚迁飞区的重要补给点。'],facts:['中文名直接来自向上反弯的鸟嘴','会像扫帚一样左右摆动嘴部觅食','黑白羽色在开阔浅滩上非常醒目'],tip:'退潮时为鸟群留下完整觅食空间，不穿越集中活动区域。'},
    {id:'great-cormorant',name:'普通鸬鹚',scientific:'Phalacrocorax carbo',emoji:'🐧',status:'无危（LC）',habitat:'海湾、河口、水库与鱼塘',image:'great-cormorant.jpg',source:'https://en.wikipedia.org/wiki/Great_cormorant',intro:['普通鸬鹚是大型深色水鸟，嘴端带钩，善于潜水捕鱼。秋冬季常能在深圳湾水面或岸边设施上看到它们。','鸬鹚的羽毛防水能力不像许多水鸭那样强，因此上岸后经常展开双翼晾晒，这也是最具代表性的观察姿态。'],facts:['潜水时主要用脚推动身体前进','张开翅膀并不一定是准备起飞，而可能是在晾羽','嘴尖的小钩有利于抓住滑溜的鱼'],tip:'不要靠近鸬鹚集中休息点，也不要投喂或干扰其捕鱼。'},
    {id:'common-greenshank',name:'青脚鹬',scientific:'Tringa nebularia',emoji:'🕊️',status:'无危（LC）',habitat:'潮滩、河口、浅水池塘',image:'common-greenshank.jpg',source:'https://en.wikipedia.org/wiki/Common_greenshank',intro:['青脚鹬腿部呈灰绿或黄绿色，嘴较长并略向上翘，是迁徙季和越冬期常见的鸻鹬类。','它会在潮沟和浅水中快速追逐小鱼、虾和水生昆虫。飞起时，白色腰部会向背部延伸，形成明显的白色楔形。'],facts:['名字来自偏青绿色的长腿','觅食动作比许多小型鹬类更快速主动','飞行时背部白色楔形是重要辨识特征'],tip:'拍摄时使用长焦镜头，不围堵正在潮沟中觅食的个体。'},
    {id:'common-redshank',name:'红脚鹬',scientific:'Tringa totanus',emoji:'🐤',status:'无危（LC）',habitat:'泥滩、盐沼、湿地水边',image:'common-redshank.jpg',source:'https://en.wikipedia.org/wiki/Common_redshank',intro:['红脚鹬具有橙红色双腿，嘴基部也带红色，是辨识度很高的中型鹬类。它们会在深圳湾潮滩和湿地水边寻找小型无脊椎动物。','飞行时翅膀后缘显出宽阔白带，配合白色腰部可与相似物种区分。受到惊扰时会发出响亮连续的警戒声。'],facts:['红色腿和红色嘴基是醒目标志','警戒心强，常最先发声提醒鸟群','宽阔的白色翼后缘在飞行时十分明显'],tip:'听到持续警戒声时说明距离过近，应立即后退。'}
  ];
  const renderCard=data=>{document.querySelector('.extra-species-panel')?.remove();const panel=document.createElement('aside');panel.className='extra-species-panel';panel.innerHTML=`<button class="extra-close" aria-label="关闭">×</button><div class="extra-title"><span>${data.emoji}</span><div><h2>${data.name}</h2><em>${data.scientific}</em></div></div><figure><img src="/birds/assets/species/${data.image}" alt="${data.name}真实照片"><figcaption>图片：Wikimedia Commons · <a href="${data.source}" target="_blank" rel="noreferrer">查看来源与许可</a></figcaption></figure><div class="extra-tags"><span>${data.status}</span><span>🐦 鸟类</span><span>${data.habitat}</span></div><section><h3>📖 详细介绍</h3>${data.intro.map(p=>`<p>${p}</p>`).join('')}</section><section><h3>✨ 趣味知识</h3>${data.facts.map((f,i)=>`<div class="extra-fact"><b>${i+1}</b><span>${f}</span></div>`).join('')}</section><div class="extra-tip"><strong>🌱 保护提示</strong><p>${data.tip}</p></div>`;document.body.appendChild(panel)};
  const mount=()=>{const strip=document.querySelector('.bottom-strip');if(!strip||strip.querySelector('.extra-species-group'))return;const group=document.createElement('div');group.className='extra-species-group';group.innerHTML=species.map(s=>`<button class="extra-strip-item" data-extra-species="${s.id}" title="${s.name}"><span>${s.emoji}</span><small>${s.name}</small></button>`).join('');strip.appendChild(group)};
  new MutationObserver(mount).observe(document.body,{childList:true,subtree:true});mount();
  document.addEventListener('click',event=>{const extra=event.target.closest('[data-extra-species]');if(extra){event.preventDefault();renderCard(species.find(s=>s.id===extra.dataset.extraSpecies));return}if(event.target.closest('.extra-close'))document.querySelector('.extra-species-panel')?.remove();else if(event.target.closest('.strip-item'))document.querySelector('.extra-species-panel')?.remove()},true);
})();
